version: '3.9'

networks:
  internet:
    name: internet
    driver: bridge
  localnet:
    name: appnet
    driver: bridge

services:
  # client:
  #     container_name: prakticum-client
  #     image: prakticum-client
  #     build:
  #         context: .
  #         dockerfile: Dockerfile.client
  #         args:
  #           CLIENT_PORT: ${CLIENT_PORT}
  #     restart: localhost
  #     ports:
  #         - "${CLIENT_PORT}:80"
  #     environment:
  #       - CLIENT_PORT=${CLIENT_PORT}
  #       - SERVER_PORT=${SERVER_PORT}
  server:
    container_name: server
    image: prackicum-server
    build:
      context: ./packages/server
      dockerfile: Dockerfile.server
    restart: always
    env_file: ./packages/server/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '3001:3001'
    networks:
      - internet
      - localnet

  postgres:
    container_name: db
    image: postgres:16
    env_file: ./packages/server/.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${DB_USER} -d $${DB_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - localnet
