version: '3.9'

networks:
  internet:
    name: internet
    driver: bridge
  localnet:
    name: localnet
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: prakticum-nginx
    build:
      context: ./packages/nginx
      dockerfile: Dockerfile.proxy
    ports:
      - 80:80
    networks:
      - internet

  client:
    container_name: client
    image: prakticum-client
    build:
      context: ./packages/client
      dockerfile: Dockerfile.client
    restart: always
    env_file: ./packages/client/.env
    depends_on:
      server:
        condition: service_healthy
    # ports:
    #   - '3000:3000'
    networks:
      - internet

  server:
    container_name: server
    image: prackicum-server
    build:
      context: ./packages/server
      dockerfile: Dockerfile.server
    restart: always
    env_file: ./packages/server/.env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001']
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
    # ports:
    #   - '3001:3001'
    networks:
      - internet
      - localnet
  init-reactions:
    container_name: init-reactions
    build:
      context: ./packages/server
      dockerfile: Dockerfile.server
    depends_on:
      server:
        condition: service_healthy
    environment:
      - API_URL=http://server:3001/api/v2/reactions
    healthcheck:
      test:
        ['CMD', 'node', '-e', "process.exit(!!require('fs').existsSync('/app/app/scripts/init.reaction.js') ? 0 : 1)"]
      interval: 5s
      timeout: 3s
      retries: 3
    command: ['node', '/app/app/scripts/init.reaction.js']
    networks:
      - internet
      - localnet
  postgres:
    container_name: db
    image: postgres:16
    env_file: ./packages/server/.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - localnet
volumes:
  pgdata:
