version: '3.9'

networks:
  internet:
    name: internet
    driver: bridge
  localnet:
    name: appnet
    driver: bridge

services:
  client:
    container_name: client
    image: prakticum-client
    build:
      context: ./packages/client
      dockerfile: Dockerfile.client
    restart: always
    env_file: ./packages/client/.env
    # depends_on:
    #   server:
    #     condition: service_healthy
    ports:
      - '3000:3000'
    networks:
      - localnet

  server:
    container_name: server
    image: prackicum-server
    build:
      context: ./packages/server
      dockerfile: Dockerfile.server
    restart: always
    env_file: ./packages/server/.env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001']
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '3001:3001'
    networks:
      - internet
      - localnet

  postgres:
    container_name: db
    image: postgres:16
    env_file: ./packages/server/.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - localnet
