name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/molochkovsa/pacman.praktikum.yandex

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    outputs:
      owner_lc: ${{ steps.set_owner.outputs.owner_lc }}

    steps:
      - uses: actions/checkout@v3

      - name: Set owner lower case
        id: set_owner
        run: echo "owner_lc=${OWNER,,}" >> $GITHUB_OUTPUT
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client
        uses: docker/build-push-action@v5
        with:
          context: ./packages/client
          file: ./packages/client/Dockerfile.client
          push: true
          tags: ghcr.io/${{ steps.set_owner.outputs.owner_lc }}/${{ github.event.repository.name }}/client:${{ github.sha }}

      - name: Build and push server
        uses: docker/build-push-action@v5
        with:
          context: ./packages/server
          file: ./packages/server/Dockerfile.server
          push: true
          tags: ghcr.io/${{ steps.set_owner.outputs.owner_lc }}/${{ github.event.repository.name }}/server:${{ github.sha }}

      - name: Build and push nginx
        uses: docker/build-push-action@v5
        with:
          context: ./packages/nginx
          file: ./packages/nginx/Dockerfile.proxy
          push: true
          tags: ghcr.io/${{ steps.set_owner.outputs.owner_lc }}/${{ github.event.repository.name }}/nginx:${{ github.sha }}

  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest

    env:
      OWNER_LC: ${{ needs.build-and-publish.outputs.owner_lc }}

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.YC_VM_HOST }}
          username: ${{ secrets.YC_VM_USER }}
          key: ${{ secrets.YC_VM_SSH_KEY }}
          script: |
            cd /home/joy-pixels

            sed -i "s|ghcr.io.*/nginx:.*|ghcr.io/${{ env.OWNER_LC }}/${{ github.event.repository.name }}/nginx:${{ github.sha }}|" docker-compose.yml
            sed -i "s|ghcr.io.*/client:.*|ghcr.io/${{ env.OWNER_LC }}/${{ github.event.repository.name }}/client:${{ github.sha }}|" docker-compose.yml
            sed -i "s|ghcr.io.*/server:.*|ghcr.io/${{ env.OWNER_LC }}/${{ github.event.repository.name }}/server:${{ github.sha }}|" docker-compose.yml

            docker-compose pull
            docker-compose up -d


