# name: Deploy to Server

# on:
#   push:
#     branches:
#       - main  # можно указать нужную ветку

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Deploy via SSH
#         uses: appleboy/ssh-action@v0.1.9
#         with:
#           host: ${{ secrets.SERVER_HOST }}      
#           username: ${{ secrets.SERVER_USER }}  
#           key: ${{ secrets.SERVER_SSH_KEY }}                             
#           script: |
#             cd /path/to/your/docker-compose-folder
#             docker-compose pull
#             docker-compose up -d


