# name: Autodeploy to Yandex Cloud

# on:
#   push:
#     branches: [main]
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Set up SSH key
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.YC_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa

#       - name: Add server to known_hosts
#         run: |
#           ssh-keyscan -H ${{ secrets.YC_INSTANCE_IP }} >> ~/.ssh/known_hosts

#       - name: Copy files to server
#         run: |
#           rsync -avz --delete ./docker-compose.yml ${{ secrets.YC_SSH_USER }}@${{ secrets.YC_INSTANCE_IP }}:/home/${{ secrets.YC_SSH_USER }}/app/

#       - name: SSH into server and deploy
#         run: |
#           ssh ${{ secrets.YC_SSH_USER }}@${{ secrets.YC_INSTANCE_IP }} << 'EOF'
#             cd ~/app
#             echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
#             docker compose pull
#             docker compose down
#             docker compose up -d
#           EOF

   